config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :texts
  resources :links
  resources :file_names
  resources :locations
  resources :tags
  resources :things
  mount Upmin::Engine => '/admin'
  root to: 'home#index'
  get 'search', to: 'home#index'
  devise_for :users
  resources :users
end

app/models/thing.rb
require 'elasticsearch/model'

class Thing < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  has_many :thing_tags
  has_many :tags, through: :thing_tags

  has_many :thing_locations
  has_many :locations, through: :thing_locations

  has_many :thing_files
  has_many :file_names, through: :thing_files

  has_many :thing_links
  has_many :links, through: :thing_links

  has_many :thing_texts
  has_many :texts, through: :thing_texts

  validates :name, presence: true
  validates :description, presence: true

  settings index: { number_of_shards: 1 } do
    mappings dynamic: 'false' do
      indexes :name, analyzer: 'russian', index_options: 'offsets'
      indexes :feature, analyzer: 'russian'
      indexes :abbreviation, analyzer: 'russian'
      indexes :description, analyzer: 'russian'
    end
  end

  def self.search(query)
    __elasticsearch__.search(
      {
        query: {
          multi_match: {
            query: query,
            fields: ['name^10', 'feature' ,'abbreviation' , 'description']
          }
        },
        highlight: {
          pre_tags: ['<em>'],
          post_tags: ['</em>'],
          fields: {
            name: {},
            feature: {},
            abbreviation: {},
            description: {}
          }
        }
      }
    )
  end
end

# Delete the previous index in Elasticsearch
Thing.__elasticsearch__.client.indices.delete index: Thing.index_name rescue nil

# Create the new index with the new mapping
Thing.__elasticsearch__.client.indices.create \
  index: Thing.index_name,
  body: { settings: Thing.settings.to_hash, mappings: Thing.mappings.to_hash }


Thing.import

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_thing, only: [:show, :edit, :update, :destroy]

  def index
    @current_user = current_user if current_user
    if params[:name] || params[:feature] || params[:abbreviation]
      things = Thing.where(user_id: @current_user.id)
       @things = things.search(params[:name], params[:feature], params[:abbreviation])
    else
      @things = Thing.where(user_id: @current_user.id)
    end
  end

  def show
  end

  def new
    @thing = Thing.new
  end

  def edit
  end

  def create
    @thing = Thing.new(thing_params)

    respond_to do |format|
      if @thing.save
        format.html { redirect_to @thing, notice: 'Thing was successfully created.' }
        format.json { render :show, status: :created, location: @thing }
      else
        format.html { render :new }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @thing.update(thing_params)
        format.html { redirect_to @thing, notice: 'Thing was successfully updated.' }
        format.json { render :show, status: :ok, location: @thing }
      else
        format.html { render :edit }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @thing.destroy
    respond_to do |format|
      format.html { redirect_to things_url, notice: 'Thing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thing
      @thing = Thing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thing_params
      params.require(:thing).permit(:name, :feature, :abbreviation, :description).merge(user_id: current_user.id)
    end
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/things/_form.html.haml
= simple_form_for(@thing) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :feature
    = f.input :abbreviation
    = f.input :description

  .form-actions
    = f.button :submit, data: { disable_with: "Please wait..." }, :class => 'btn btn-primary'

app/views/things/edit.html.haml
%h1 Editing thing

= render 'form'

%br
= link_to 'Back', @thing

app/views/things/index.html.haml
%h1 Things
%br
%table{:style=>"width: 80%"}
  %thead
    %tr
      %th id
      %th Name
      %th Feature
      %th Abbreviation
      %th
      %th
      %th

  %tbody
    - @things.each do |thing|
      %tr
        %td= thing.id
        %td= thing.name
        %td= thing.feature
        %td= thing.abbreviation
        %td= link_to 'Show', thing
        %td= link_to 'Edit', edit_thing_path(thing)
        %td= link_to 'Destroy', thing, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Thing', new_thing_path

app/views/things/new.html.haml
%h1 New thing

= render 'form'

= link_to 'Back', things_path

app/views/things/show.html.haml
%h4
  = @thing.name.mb_chars.capitalize.to_s
  = @thing.feature
  = @thing.abbreviation
%p
  %b Description:
  = @thing.description
%p
  %b Tags:
  - @thing.tags.each do |tag|
    = tag.name
    %small
      = " | "
    
      = link_to 'Edit', "/tags/#{tag.id}/edit?thing_id=#{@thing.id}"
      = " | "
      = link_to 'x', "/tags/#{tag.id}?thing_id=#{@thing.id}", :method => :delete, :data => { :confirm => 'Are you sure?' }
      = " | "
  %small
    = link_to 'Add tag', new_tag_path(thing_id: params[:id])
%p
  %b Text:
  - @thing.texts.each do |text|
    %br
    %p!= text.text
    %small
      = " | "
      = link_to 'Edit', "/texts/#{text.id}/edit?thing_id=#{@thing.id}"
      = " | "
      = link_to 'x', "/texts/#{text.id}?thing_id=#{@thing.id}", :method => :delete, :data => { :confirm => 'Are you sure?' }
      = " | "
  %small
    = link_to 'Add text', new_text_path(thing_id: params[:id]) 

%p
  %b Location:
  - @thing.locations.each do |location|
    %br
    = location.name
    %small
      = " | "
      = link_to 'Edit', "/locations/#{location.id}/edit?thing_id=#{@thing.id}"
      = " | "
      = link_to 'x', "/locations/#{location.id}?thing_id=#{@thing.id}", :method => :delete, :data => { :confirm => 'Are you sure?' }
      = " | "
  %small
    = link_to 'Add location', new_location_path(thing_id: params[:id])

%p
  %b File:
  - @thing.file_names.each do |file|
    %br
    = file.storage + "/" + file.name
    %small
      = " | "
      = link_to 'Edit', "/file_names/#{file.id}/edit?thing_id=#{@thing.id}"
      = " | "
      = link_to 'x', "/file_names/#{file.id}?thing_id=#{@thing.id}", :method => :delete, :data => { :confirm => 'Are you sure?' }
      = " | "
  %small
    = link_to 'Add file', new_file_name_path(thing_id: params[:id])

%p
  %b Link:
  - @thing.links.each do |link|
    %br
    = link.name
    %small
      = " | "
      = link_to 'Edit', "/links/#{link.id}/edit?thing_id=#{@thing.id}"
      = " | "
      = link_to 'x', "/links/#{link.id}?thing_id=#{@thing.id}", :method => :delete, :data => { :confirm => 'Are you sure?' }
      = " | "
  %small
    = link_to 'Add link', new_link_path(thing_id: params[:id])


= link_to 'Edit', edit_thing_path(@thing)
\|
= link_to 'Back', things_path