config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :texts
  resources :links
  resources :file_names
  resources :locations
  resources :tags
  resources :things
  mount Upmin::Engine => '/admin'
  root to: 'home#index'
  get 'search', to: 'home#index'
  devise_for :users
  resources :users
end

app/models/tag.rb
class Tag < ActiveRecord::Base  
  has_many :thing_tags, dependent: :destroy
  has_many :things, through: :thing_tags

  validates :name, presence: true
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tag, only: [:edit, :update, :destroy]
  before_action :set_thing, only: [:new, :create, :edit, :update, :destroy]

  def new
    @tag = Tag.new
  end

  def edit
  end

  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        ThingTag.create(thing_id: params[:thing_id], tag_id: @tag.id)
        format.html { redirect_to @thing, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @thing }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @thing, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @thing }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to @thing, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    def set_thing
      @thing = Thing.find(params[:thing_id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.haml
= simple_form_for @tag, url: "/tags?thing_id=#{@thing.id}" do |f|
  = f.error_notification
  .form-inputs
    = f.input :name
  .form-actions
    = f.button :submit, data: { disable_with: "Please wait..." }, :class => 'btn btn-primary'

app/views/tags/edit.html.haml
%h1 Editing tag

= simple_form_for @tag, url: "/tags/#{@tag.id}?thing_id=#{@thing.id}" do |f|
  = f.error_notification
  .form-inputs
    = f.input :name
  .form-actions
    = f.button :submit, data: { disable_with: "Please wait..." }, :class => 'btn btn-primary'

%br
= link_to 'Back', @thing

app/views/tags/new.html.haml
%h1 New tag

= render 'form'

%br
= link_to 'Back', thing_path(@thing)